apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flbasicorg1.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flbasicorg1.labels" . | nindent 4 }}
spec:
  {{- if not .Values.flbasicorg1.autoscaling.enabled }}
  replicas: {{ .Values.flbasicorg1.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flbasicorg1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flbasicorg1.labels" . | nindent 8 }}
    spec:
      {{- with .Values.flbasicorg1.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.flbasicorg1.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.flbasicorg1.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flbasicorg1.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.flbasicorg1.podSecurityContext | nindent 8 }}
      containers:
        - name: flbasicorg1
          securityContext:
            {{- toYaml .Values.flbasicorg1.securityContext | nindent 12 }}
          image: "{{ .Values.flbasicorg1.image.repository }}:{{ .Values.flbasicorg1.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flbasicorg1.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.flbasicorg1.service.containerPort }}
              protocol: {{ .Values.flbasicorg1.service.protocol }}
          resources:
            {{- toYaml .Values.flbasicorg1.resources | nindent 12 }}
          # command: ["CHAINCODE_ID=$(cat ../chaincodeids/chaincode_id.txt)"]
          # command: ["sleep", "infinity"]
          command:
          - /bin/sh
          - -c
          - |
            echo "waiting for CHAINCODE_ID"
            sleep 270
            export CHAINCODE_ID=$(cat ../chaincodeids/flbasic1.txt)
            echo "$CHAINCODE_ID"
            env
            ./fldltcc.out
            echo "teleiwse?"
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: {{ .Values.flbasicorg1.envVars.CHAINCODE_SERVER_ADDRESS | quote }}
          volumeMounts:
            - mountPath: /chaincodeids
              name: fabricfiles
              subPath: chaincodeids
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: hlfpvchelm
