apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flbasicorg2.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flbasicorg2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.flbasicorg2.autoscaling.enabled }}
  replicas: {{ .Values.flbasicorg2.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flbasicorg2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flbasicorg2.labels" . | nindent 8 }}
    spec:
      {{- with .Values.flbasicorg2.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.flbasicorg2.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.flbasicorg2.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flbasicorg2.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.flbasicorg2.podSecurityContext | nindent 8 }}
      containers:
        - name: flbasicorg2
          securityContext:
            {{- toYaml .Values.flbasicorg2.securityContext | nindent 12 }}
          image: "{{ .Values.flbasicorg2.image.repository }}:{{ .Values.flbasicorg2.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flbasicorg2.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.flbasicorg2.service.containerPort }}
              protocol: {{ .Values.flbasicorg2.service.protocol }}
          resources:
            {{- toYaml .Values.flbasicorg2.resources | nindent 12 }}
          command:
          - /bin/sh
          - -c
          - |
            echo "waiting for CHAINCODE_ID"
            sleep 270
            export CHAINCODE_ID=$(cat ../chaincodeids/flbasic2.txt)
            echo "$CHAINCODE_ID"
            env
            ./fldltcc.out
            echo "teleiwse?"
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: {{ .Values.flbasicorg2.envVars.CHAINCODE_SERVER_ADDRESS | quote }}
          volumeMounts:
            - mountPath: /chaincodeids
              name: fabricfiles
              subPath: chaincodeids
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: hlfpvchelm
